database_name  = "DEV_DB"
warehouse_name = "DEV_WH"
warehouse_size = "X-SMALL"
role_name      = "DEV_ROLE"
SNOWFLAKE_ORGANIZATION_NAME= "YILFLZT"
SNOWFLAKE_ACCOUNT_NAME= "KEB73082"
SNOWFLAKE_USER = "ZACKHADD"
