name: Trigger Dev/Prod Workflow

on:
  pull_request:
    branches:
      - dev
      - prod
    types:
      - closed 
jobs:
  trigger-workflow:
    name: 'Trigger Dev/Prod Workflow'
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Target Branch
        run: |
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"

      - name: Debug Secrets
        run: |
          if [[ -n "$ARM_SAS_TOKEN" ]]; then
            echo "✅ ARM_SAS_TOKEN is set"
          else
            echo "❌ ARM_SAS_TOKEN is missing"
          fi

      - name: Trigger Dev/Prod Workflow
        uses: actions/github-script@v6
        with:
#          github-token: ${{ secrets.REPO_PAT }}  # Use the PAT for authentication if needed
          script: |
            try {
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'test_terraform.yml',  // Name of the second workflow
                ref: '${{ github.event.pull_request.base.ref }}',  // Target branch (dev or prod)
              });
              console.log(`Workflow dispatch successful! Status: ${response.status}`);
            } catch (error) {
              console.error(`Error triggering workflow: ${error.message}`);
              console.error(`Error details: ${JSON.stringify(error, null, 2)}`);
              throw error;
            }